services:
  - type: web
    name: line-chatgpt-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: your_channel_secret
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your_channel_access_token


