services:
  - type: web
    name: line-chatbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your-line-access-token
      - key: LINE_CHANNEL_SECRET
        value: your-line-secret
